poller:
  interval: 5s
  log-level: debug
db:
  address: "mongodb://mongodb:27017"
  db-name: staking-api-service
btc:
  endpoint: bitcoindsim:18443 # use port 18332 for testnet, 8332 for mainnet
  disable-tls: true
  net-params: regtest
  rpc-user: rpcuser
  rpc-pass: rpcpass
queue:
  queue_user: user # can be replaced by values in .env file
  queue_password: password
  url: "rabbitmq:5672"
  processing_timeout: 5 # 5 second
  msg_max_retry_attempts: 10
  requeue_delay_time: 300
  queue_type: quorum
metrics:
  host: 0.0.0.0
  port: 2112
