# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

[db-config]
# The network chain ID
db-name = "staking-api-service"
# The keyring's backend, where the keys are stored (os|file|kwallet|pass|test|memory)
address = "mongodb://mongodb:27017"

[btc-config]
# Btc node host
host = "bitcoindsim:18443"
# Btc node user
user = "rpcuser"
# Btc node password
pass = "rpcpass"
# Btc network (testnet3|mainnet|regtest|simnet|signet)
network = "regtest"

[params-config]
covenant_public_keys = ["0342301c4fdb5b1ab27a80a04d95c782f720874265889412a80d270feeb456f1f7", "03a4d2276a2a09f0e14d6a74901fec0aab3d1edf0dd22a690260acca48f5d5b3c0", "02707f3d6bf2334ecb7c336fc7babd400afa9132a34f84406b28865d06e0ba81e8"]
# The quorum of the covenants required to sign the transaction
covenant_quorum = 2
# The magic bytes of the network
magic_bytes = "62627434"

[remote-signer-config]
# The list of signer urls in the format http://covenant_pk@signer_host:port
urls = ["http://0342301c4fdb5b1ab27a80a04d95c782f720874265889412a80d270feeb456f1f7@covenant-signer:9791", "http://03a4d2276a2a09f0e14d6a74901fec0aab3d1edf0dd22a690260acca48f5d5b3c0@covenant-signer:9791", "http://02707f3d6bf2334ecb7c336fc7babd400afa9132a34f84406b28865d06e0ba81e8@covenant-signer:9791"]
# The timeout of each request to the remote signing server
timeout = 10